package com.Vaishnav.employeetracker.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.Vaishnav.employeetracker.data.Employee
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

object PdfGenerator {

    fun generateEmployeeReport(
        context: Context,
        employee: Employee,
        daysPresent: Int,
        lateDays: Int,
        taskCompletionRate: Int
    ): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size in points (approx)
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // Define Colors
        val primaryColor = Color.parseColor("#6366F1")
        val textColor = Color.BLACK
        val grayColor = Color.DKGRAY

        // Title
        paint.color = primaryColor
        paint.textSize = 24f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Employee Record", 50f, 60f, paint)

        // Header Line
        paint.color = Color.LTGRAY
        paint.strokeWidth = 2f
        canvas.drawLine(50f, 80f, 545f, 80f, paint)

        // Employee Details Section
        paint.color = textColor
        paint.textSize = 18f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Personal Information", 50f, 130f, paint)

        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT
        var yPos = 160f
        
        drawDetailRow(canvas, paint, "Name:", employee.name, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Employee ID:", employee.employeeId, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Designation:", employee.designation, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Department:", employee.department, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Email:", employee.email, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Phone:", employee.phone, 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Joining Date:", DateTimeHelper.formatDate(employee.joiningDate), 50f, yPos)

        // Stats Section
        yPos += 50f
        paint.color = textColor
        paint.textSize = 18f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Performance Summary", 50f, yPos, paint)

        yPos += 30f
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT
        
        drawDetailRow(canvas, paint, "Attendance (Present):", "$daysPresent days", 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Late Arrivals:", "$lateDays days", 50f, yPos)
        yPos += 25f
        drawDetailRow(canvas, paint, "Task Completion:", "$taskCompletionRate%", 50f, yPos)
        
        // Footer
        val footerY = 800f
        paint.color = grayColor
        paint.textSize = 10f
        canvas.drawText("Generated by EmployeeTracker", 50f, footerY, paint)
        canvas.drawText("Date: ${DateTimeHelper.getCurrentDate()}", 400f, footerY, paint)

        pdfDocument.finishPage(page)

        // Save File
        val fileName = "EmployeeReport_${employee.employeeId}.pdf"
        val file = File(context.getExternalFilesDir(null), fileName)

        try {
            val fileOutputStream = FileOutputStream(file)
            pdfDocument.writeTo(fileOutputStream)
            pdfDocument.close()
            fileOutputStream.close()
            return file
        } catch (e: IOException) {
            e.printStackTrace()
            pdfDocument.close()
            return null
        }
    }

    private fun drawDetailRow(canvas: Canvas, paint: Paint, label: String, value: String, x: Float, y: Float) {
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(label, x, y, paint)
        paint.typeface = Typeface.DEFAULT
        canvas.drawText(value, x + 150f, y, paint)
    }
}
